apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-53o2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-53o2
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-53o2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-53o2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-53o2
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fxvs-tenant/rhtap-demo-app/hacbs-test-project-53o2@sha256:9d7f82a1bfaff3f9214ab893a9cdf537e7c1cd12851cc8ef1c301952a744e053
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
